// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnhSooFU7Kne93-Bd07rZpQ8pJ2LSdmFE',
    appId: '1:530920057497:web:f6b0b0a85f473caf8ca608',
    messagingSenderId: '530920057497',
    projectId: 'chatter-stream-demo',
    authDomain: 'chatter-stream-demo.firebaseapp.com',
    storageBucket: 'chatter-stream-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWpKedtRPTPuvDLwLJtTqutmvjQ6W7XiQ',
    appId: '1:530920057497:android:fa15d5e79eef575c8ca608',
    messagingSenderId: '530920057497',
    projectId: 'chatter-stream-demo',
    storageBucket: 'chatter-stream-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcXNEaoq1DuzGCpuRAYU17AECsbcoiB-Y',
    appId: '1:530920057497:ios:ad3a55cd1b083b158ca608',
    messagingSenderId: '530920057497',
    projectId: 'chatter-stream-demo',
    storageBucket: 'chatter-stream-demo.appspot.com',
    androidClientId: '530920057497-se4jnrc3tt8s5p80a7h6074da4i9l5vt.apps.googleusercontent.com',
    iosClientId: '530920057497-4orfrnok69irce8ap3dle91ecds0b5kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatterStreamDemo',
  );
}
